# save-session.ps1
# Saves a complete test session as a markdown log file
param()

$timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm'
$fileStamp = Get-Date -Format 'yyyy-MM-dd-HHmm'
$logDir = "test-results"
$logFile = "$logDir\session-$fileStamp.md"

New-Item -ItemType Directory -Force -Path $logDir | Out-Null

Write-Host ""
Write-Host "=== SESSION LOGGER ===" -ForegroundColor Cyan
Write-Host "Timestamp: $timestamp"
Write-Host ""

# Step 1: Skill
Write-Host "Which skill did you test?" -ForegroundColor Yellow
Write-Host "  1.  market-intelligence"
Write-Host "  2.  competitive-analysis"
Write-Host "  3.  github-intelligence"
Write-Host "  4.  onchain-pulse"
Write-Host "  5.  gtm-checklist"
Write-Host "  6.  metrics-that-matter"
Write-Host "  7.  tokenomics-audit"
Write-Host "  8.  /analyze-market (command)"
Write-Host "  9.  /audit-project (command)"
Write-Host "  10. gtm-advisor (agent)"
Write-Host "  11. other"
$skillChoice = Read-Host "Enter number"
$skillName = switch ($skillChoice) {
    "1"  { "market-intelligence" }
    "2"  { "competitive-analysis" }
    "3"  { "github-intelligence" }
    "4"  { "onchain-pulse" }
    "5"  { "gtm-checklist" }
    "6"  { "metrics-that-matter" }
    "7"  { "tokenomics-audit" }
    "8"  { "/analyze-market command" }
    "9"  { "/audit-project command" }
    "10" { "gtm-advisor agent" }
    default { "other" }
}

# Step 2: AI tool
Write-Host ""
Write-Host "Which AI tool did you use?" -ForegroundColor Yellow
Write-Host "  1. Claude Code (recommended)"
Write-Host "  2. Claude.ai"
Write-Host "  3. Gemini CLI"
Write-Host "  4. DeepSeek"
Write-Host "  5. Other"
$aiChoice = Read-Host "Enter number"
$aiTool = switch ($aiChoice) {
    "1" { "Claude Code" }
    "2" { "Claude.ai" }
    "3" { "Gemini CLI" }
    "4" { "DeepSeek" }
    default { "Other" }
}

# Step 3: Live data
Write-Host ""
Write-Host "Paste live data (if any)." -ForegroundColor Yellow
Write-Host "If none, just type END and press Enter."
Write-Host "Otherwise paste your data, then type END on a new line and press Enter:"
$liveData = @()
while ($true) {
    $line = Read-Host
    if ($line -eq "END") { break }
    $liveData += $line
}

# Step 4: Prompt
Write-Host ""
Write-Host "Paste the prompt you sent to the AI." -ForegroundColor Yellow
Write-Host "When done, type END on a new line and press Enter:"
$prompt = @()
while ($true) {
    $line = Read-Host
    if ($line -eq "END") { break }
    $prompt += $line
}

# Step 5: Response
Write-Host ""
Write-Host "Paste the AI response." -ForegroundColor Yellow
Write-Host "When done, type END on a new line and press Enter:"
$response = @()
while ($true) {
    $line = Read-Host
    if ($line -eq "END") { break }
    $response += $line
}

# Step 6: Notes
Write-Host ""
$notes = Read-Host "Any notes? (press Enter to skip)"

# Build log
$liveSection   = if ($liveData.Count -gt 0) { $liveData -join "`r`n" } else { "None" }
$promptSection = $prompt -join "`r`n"
$respSection   = $response -join "`r`n"
$notesSection  = if ($notes) { $notes } else { "None" }

$lines = @(
    "# Test Session Log",
    "**Skill tested:** $skillName",
    "**AI tool:** $aiTool",
    "**Timestamp:** $timestamp",
    "",
    "---",
    "",
    "## Live Data Fetched",
    "",
    $liveSection,
    "",
    "---",
    "",
    "## Prompt Sent to AI",
    "",
    $promptSection,
    "",
    "---",
    "",
    "## AI Response",
    "",
    $respSection,
    "",
    "---",
    "",
    "## Notes",
    "",
    $notesSection,
    "",
    "---",
    "Generated by save-session.ps1 - solana-founder-marketing-skill"
)

$lines | Out-File -FilePath $logFile -Encoding UTF8

Write-Host ""
Write-Host "Saved to: $logFile" -ForegroundColor Green
Write-Host "Open in VS Code: code $logFile" -ForegroundColor Cyan
